# Generated by Django 4.2.4 on 2023-10-02 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 19, 17, 32, 819561, tzinfo=datetime.timezone.utc)),
        ),
    ]
