# Generated by Django 4.2.4 on 2023-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_comment_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
